#!/bin/bash
# This script runs as a daemon and makes changes to the cgroups
# parameters based on information in the files created and modified
# by other scripts. Joseph Santaniello <js@syse.no> 2013-02-13

# First make sure this is only instance of the script running:
LOCKFILE=/tmp/ourcrazylockfilename
if [ -e ${LOCKFILE} ] && kill -0 `cat ${LOCKFILE}`; then
	echo "Instance of ${BASH_SOURCE[0]} already running! Exiting."
	exit 1
fi
# Make sure our lockfile gets rm'ed and claim it.
trap "rm -f ${LOCKFILE}; exit" INT TERM EXIT
echo $$ > ${LOCKFILE}
# cd to where we want to be so subdirs are where we expect.
cd "$(dirname ${BASH_SOURCE[0]})"
# Source our common functions
. common.sh

# Check that there is at least one mounted subsystem
chk_subsys

# Enter the loop that waits for changes to files in the groups directory
inotifywait -q -m --format '%e %w%f' --exclude '\.(disabled)' -e create -e delete -e move -e modify groups | while read line; do
	read EVENT FILENAME <<<$(echo $line)
	case $EVENT in
		CREATE|MOVED_TO|MODIFIED|MODIFY)
			create $FILENAME
			;;
		DELETE|MOVED_FROM)
			delete $FILENAME
			;;
	esac
	# Now rebuild the cgrules.conf file
	construct_cgrules
	# Restart the cgrulesengd
	# This is ugly... but we don't have to deal with PID and flaky SIGUSR2.
	killall cgrulesengd > /dev/null 2>&1; cgrulesengd
done

# Delete the lockfile
rm -f ${LOCKFILE}
