#!/bin/bash
# This script runs as a daemon and makes changes to the cgroups
# parameters based on information in the files created and modified
# by other scripts. Joseph Santaniello <js@syse.no> 2013-02-13

# cd to where we want to be so subdirs are where we expect.
cd "$(dirname ${BASH_SOURCE[0]})"

CG=/sys/fs/cgroup

# Check that there is at least one mounted subsystem
function chk_subsys {
	if [ `lssubsys -m $c | wc -l` -lt 1 ]; then
		echo "No mounted cgroup subsystems found!" | logger -s -t CGROUP
		return 1
	fi
}
chk_subsys
#echo $?

function create {
	g="$(basename $1 .conf)"
	# Initialize the cgrules.conf for this group
	echo -n > cgrules/$g
	u=$g
	PROCESSED_SUBSYSTEM=""
	# Create group dir in mounted subsystems that the conf file
	# has an entry for. Iterate over conf and make if subsys is mounted.
	for LINE in `cat $1 | sort | grep -v "#"`; do
		# Get the conf values for this group and subsys
		read SUBSYS_NAME VALUE <<<$(echo $LINE|tr -s "=" " ")
		read SUBSYS NAME <<<$(echo $SUBSYS_NAME|tr -s "." " ")
		# Now check if SUBSYS is mounted
		if (lssubsys -m | grep -qw $SUBSYS); then
			# make the group in this subsystem
			SUBSYS_DIR=`lssubsys $SUBSYS -m|cut -d " " -f2`
			echo mkdir -p $SUBSYS_DIR/$g
			# set values
			echo echo $VALUE X $SUBSYS_DIR/$g/$SUBSYS.$NAME
			# add to cgrules.conf if we don't already have a
			# line for this controller. Some controllers have
			# multiple subsystem values and we could be here
			# several times in the enclosing loop.
			# use groupname for first line
			if [ "$PROCESSED_SUBSYS" != $SUBSYS ]; then
				echo -n $u >> cgrules/$g
				# and % for subsequent.
				u="%" # Needed because of silly cgrules.conf limitations
				echo $u
				echo " "$SUBSYS $g/ >> cgrules/$g
			fi
		else
			echo $SUBSYS not mounted. Skipping...
		fi
		PROCESSED_SUBSYS=$SUBSYS
	done

}

function delete {
	echo Del $1
}


# Enter the loop that waits for changes to files in the groups directory
inotifywait -q -m --format '%e %w%f' --exclude '\.(disabled)' -e create -e delete -e move -e modify groups | while read line; do
	read EVENT FILENAME <<<$(echo $line)
	case $EVENT in
		CREATE|MOVED_TO|MODIFIED)
			create $FILENAME
			;;
		DELETE|MOVED_FROM)
			delete $FILENAME
			;;
	esac
done
exit 0

# Initialize the /etc/cgrules.conf FIXME here we need to deal with changes
#echo -n > /etc/cgrules.conf

# Get list of group confs
for f in groups/*.conf; do
	g="$(basename $f .conf)"
	u=$g
	PROCESSED_SUBSYSTEM=""
	# Create group dir in mounted subsystems that the conf file
	# has an entry for. Iterate over conf and make if subsys is mounted.
	for LINE in `grep -v "#" $f`; do
		# Get the conf values for this group and subsys
		read SUBSYS_NAME VALUE <<<$(echo $LINE|tr -s "=" " ")
		read SUBSYS NAME <<<$(echo $SUBSYS_NAME|tr -s "." " ")
		# Now check if SUBSYS is mounted
		if (lssubsys -m | grep -qw $SUBSYS); then
			# make the group in this subsystem
			SUBSYS_DIR=`lssubsys $SUBSYS -m|cut -d " " -f2`
			mkdir -p $SUBSYS_DIR/$g
			# set values
			echo $VALUE > $SUBSYS_DIR/$g/$SUBSYS.$NAME
			# add to cgrules.conf if we don't already have a
			# line for this controller. Some controllers have
			# multiple subsystem values and we could be here
			# several times in the enclosing loop.
			# use groupname for first line
			if [ "$PROCESSED_SUBSYS" != $SUBSYS ]; then
				echo -n $u >> /etc/cgrules.conf
				# and % for subsequent.
				u="%" # Needed because of silly cgrules.conf limitations
				echo " "$SUBSYS $g/ >> /etc/cgrules.conf
			fi
		fi
		PROCESSED_SUBSYS=$SUBSYS
	done
	echo >> /etc/cgrules.conf
done

# Remove disabled groups
for f in groups/*.disabled; do
	g="$(basename $f .disabled)"
	for LINE in `lscgroup | grep :/$g$`; do
		cgdelete $LINE
	done
done

# Add our cgrules.footer
[ -f /etc/cgrules.conf.footer ] && cat /etc/cgrules.conf.footer >> /etc/cgrules.conf

# Add catchall to cgrules.conf
echo "*" "*" catchall/ >> /etc/cgrules.conf

# This is ugly... but we don't have to deal with PID and flaky SIGUSR2.
killall cgrulesengd > /dev/null 2>&1; cgrulesengd

