#!/bin/bash
# This script runs as a daemon and makes changes to the cgroups
# parameters based on information in the files created and modified
# by other scripts. Joseph Santaniello <js@syse.no> 2013-02-13

# cd to where we want to be so subdirs are where we expect.
cd "$(dirname ${BASH_SOURCE[0]})"
#FIXME add some sort of lock to ensure only on instance is running
# Source our common functions
. common.sh

CG=/sys/fs/cgroup

# Check that there is at least one mounted subsystem
chk_subsys

# Enter the loop that waits for changes to files in the groups directory
inotifywait -q -m --format '%e %w%f' --exclude '\.(disabled)' -e create -e delete -e move -e modify groups | while read line; do
	read EVENT FILENAME <<<$(echo $line)
	case $EVENT in
		CREATE|MOVED_TO|MODIFIED)
			create $FILENAME
			;;
		DELETE|MOVED_FROM)
			delete $FILENAME
			;;
	esac
	# Now rebuild the cgrules.conf file
	construct_cgrules
	# Restart the cgrulesengd
	# This is ugly... but we don't have to deal with PID and flaky SIGUSR2.
	killall cgrulesengd > /dev/null 2>&1; cgrulesengd
done
exit 0

